sudo: true
language: node_js
node_js:
  - 12.12.0 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
script:
  - hexo generate # generate static files
after_script:
    - cd ./public
    - git init
    - git config user.name "ThunderboltSmile"
    - git config user.email "xc93224@yeah.net"
    - git add .
    - git commit -m "Update docs"
    - git push --force --quiet "https://${GH_TOKEN}@github.com/ThunderboltSmile/thunderboltsmile.github.io.git" master:master

# test
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN
#   keep-history: true
#   on:
#     branch: master
#   local-dir: public